debug-mode: false # This setting lets you see more information on errors and other issues.

database:
  type: MYSQL # MYSQL, SQLITE, FLAT_FILE, MONGO
  host: "jdbc:mysql://localhost:3306/test"
  port: 3306
  name: "test"
  user: "root"
  password: "root"


command:
  cooldowns:
    enabled: true # This setting lets you enable or disable the cooldowns.
    bypass: true # This setting lets you set the cooldowns bypass.
    bypass-permission: "tofucore.command.cooldowns.bypass" # If the setting above is true, you can set the permission to bypass the cooldowns.